//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zl_boss_alien.html
sprites/3dmflared.spr
gfx/env/hkbk.tga
gfx/env/hkdn.tga
gfx/env/hkft.tga
gfx/env/hklf.tga
gfx/env/hkrt.tga
gfx/env/hkup.tga
sprites/zl/npc/alien/light.spr
models/zl/npc/alien/zl_galogramma.mdl
models/zl/npc/alien/zl_sky.mdl
maps/zl_boss_alien.bsp
